### ISSUE TITLE
garment masks in Instance-Level Garment Localization Learning

### ISSUE THREAD

**Issue by lonely0000cc** [Crayon-Shinchan/AnyDressing#2]
Thanks for your great work.
How do you get the garment masks in Instance-Level Garment Localization Learning module. Is it the same way as Garment-Enhanced Texture Learning?

**Comment by Crayon-Shinchan** [comment]
> Thanks for your great work. How do you get the garment masks in Instance-Level Garment Localization Learning module. Is it the same way as Garment-Enhanced Texture Learning?

Thank you for your attention, we can get the garment masks through any human-parsing-related method, and it is the same as the mask used by our GTL module.
